# Generated by Django 3.0.8 on 2020-07-20 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0004_auto_20200720_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_categorie',
            name='catagory_name',
        ),
    ]
