# Generated by Django 3.0.8 on 2020-07-20 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0006_sub_categorie_catagory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='sub_category',
        ),
        migrations.DeleteModel(
            name='sub_categorie',
        ),
    ]
