# Generated by Django 3.0.8 on 2020-07-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0013_auto_20200730_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='name',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
